name: Lint and test

on:
  push:
    branches-ignore: [ main ]

jobs:
  linter_and_test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=30m --config=./.golangci.pipeline.yaml --issues-exit-code=0

      - name: Test
        run: go test -v ./...